# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prior_commands.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(362, 381)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        Dialog.setFont(font)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 321, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.prior_commands = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.prior_commands.setObjectName("prior_commands")
        self.verticalLayout.addWidget(self.prior_commands)
        self.accept_deny = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.accept_deny.setOrientation(QtCore.Qt.Horizontal)
        self.accept_deny.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.accept_deny.setObjectName("accept_deny")
        self.verticalLayout.addWidget(self.accept_deny)

        self.retranslateUi(Dialog)
        self.accept_deny.accepted.connect(Dialog.accept)
        self.accept_deny.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Prior Commands"))
        self.label.setText(_translate("Dialog", "Valid Prior Commands Sent To Arduino"))
